#include "token_type.h"

#include "../lexer/group_name.h"

#include <unordered_map>

using codesh::token::token_type;
using namespace codesh::regex::group_name;

static const std::unordered_map<std::string_view, token_type> GROUP_NAME_TO_TOKEN_TYPE = {
    {IDENTIFIER_NUMBER_GROUP_NAME, token_type::IDENTIFIER_NUMBER},
    {IDENTIFIER_CUSTOM_GROUP_NAME, token_type::IDENTIFIER_CUSTOM},

    {KEYWORD_IMPORT_GROUP_NAME, token_type::KEYWORD_IMPORT},

    {SCOPE_BEGIN_GROUP_NAME, token_type::SCOPE_BEGIN},
    {SCOPE_END_GROUP_NAME, token_type::SCOPE_END},

    {KEYWORD_LET_GROUP_NAME, token_type::KEYWORD_LET},
    {KEYWORD_RETURN_GROUP_NAME, token_type::KEYWORD_RETURN},

    {OPERATOR_ADDITION_GROUP_NAME, token_type::OPERATOR_ADDITION},
    {OPERATOR_SUBTRACTION_GROUP_NAME, token_type::OPERATOR_SUBTRACTION},
    {OPERATOR_MULTIPLICATION_GROUP_NAME, token_type::OPERATOR_MULTIPLICATION},
    {OPERATOR_DIVISION_GROUP_NAME, token_type::OPERATOR_DIVISION},
    {OPERATOR_MODULO_GROUP_NAME, token_type::OPERATOR_MODULO},

    {OPERATOR_ADDITION_ASSIGNMENT_GROUP_NAME, token_type::OPERATOR_ADDITION_ASSIGNMENT},
    {OPERATOR_SUBTRACTION_ASSIGNMENT_GROUP_NAME, token_type::OPERATOR_SUBTRACTION_ASSIGNMENT},
    {OPERATOR_MULTIPLICATION_ASSIGNMENT_GROUP_NAME, token_type::OPERATOR_MULTIPLICATION_ASSIGNMENT},
    {OPERATOR_DIVISION_ASSIGNMENT_GROUP_NAME, token_type::OPERATOR_DIVISION_ASSIGNMENT},
    {OPERATOR_MODULO_ASSIGNMENT_GROUP_NAME, token_type::OPERATOR_MODULO_ASSIGNMENT},

    {OPERATOR_INCREMENT_GROUP_NAME, token_type::OPERATOR_INCREMENT},
    {OPERATOR_DECREMENT_GROUP_NAME, token_type::OPERATOR_DECREMENT},

    {OPEN_PARENTHESIS_GROUP_NAME, token_type::OPEN_PARENTHESIS},
    {CLOSE_PARENTHESIS_GROUP_NAME, token_type::CLOSE_PARENTHESIS},

    {SEMICOLON_GROUP_NAME, token_type::SEMICOLON},
    {DOT_GROUP_NAME, token_type::DOT},

    {KEYWORD_CLASS_GROUP_NAME, token_type::KEYWORD_CLASS},
    {KEYWORD_ENUM_GROUP_NAME, token_type::KEYWORD_ENUM},
    {KEYWORD_THIS_GROUP_NAME, token_type::KEYWORD_THIS},
    {KEYWORD_FUNCTION_GROUP_NAME, token_type::KEYWORD_FUNCTION},
    {KEYWORD_FUNCTION_CALL_GROUP_NAME, token_type::KEYWORD_FUNCTION_CALL},

    {KEYWORD_PUBLIC_GROUP_NAME, token_type::KEYWORD_PUBLIC},
    {KEYWORD_PRIVATE_GROUP_NAME, token_type::KEYWORD_PRIVATE},
    {KEYWORD_STATIC_GROUP_NAME, token_type::KEYWORD_STATIC},
    {KEYWORD_ABSTRACT_GROUP_NAME, token_type::KEYWORD_ABSTRACT},
    {KEYWORD_FINAL_GROUP_NAME, token_type::KEYWORD_FINAL},
    {KEYWORD_SUPER_GROUP_NAME, token_type::KEYWORD_SUPER},

    {KEYWORD_VAR_GROUP_NAME, token_type::KEYWORD_VAR},
    {KEYWORD_INTEGER_GROUP_NAME, token_type::KEYWORD_INTEGER},
    {KEYWORD_FLOAT_GROUP_NAME, token_type::KEYWORD_FLOAT},
    {KEYWORD_DOUBLE_GROUP_NAME, token_type::KEYWORD_DOUBLE},
    {KEYWORD_LONG_GROUP_NAME, token_type::KEYWORD_LONG},
    {KEYWORD_SHORT_GROUP_NAME, token_type::KEYWORD_SHORT},
    {KEYWORD_BYTE_GROUP_NAME, token_type::KEYWORD_BYTE},
    {KEYWORD_CHAR_GROUP_NAME, token_type::KEYWORD_CHAR},
    {KEYWORD_STRING_GROUP_NAME, token_type::KEYWORD_STRING},
    {KEYWORD_BOOLEAN_GROUP_NAME, token_type::KEYWORD_BOOLEAN},
    {KEYWORD_NULL_GROUP_NAME, token_type::KEYWORD_NULL},

    {KEYWORD_IF_GROUP_NAME, token_type::KEYWORD_IF},
    {KEYWORD_ELSE_GROUP_NAME, token_type::KEYWORD_ELSE},
    {KEYWORD_SWITCH_GROUP_NAME, token_type::KEYWORD_SWITCH},
    {KEYWORD_CASE_GROUP_NAME, token_type::KEYWORD_CASE},
    {KEYWORD_DEFAULT_GROUP_NAME, token_type::KEYWORD_DEFAULT},

    {OPERATOR_EQUALS_GROUP_NAME, token_type::OPERATOR_EQUALS},
    {OPERATOR_AGAINST_GROUP_NAME, token_type::OPERATOR_AGAINST},
    {OPERATOR_NOT_GROUP_NAME, token_type::OPERATOR_NOT},
    {OPERATOR_GREATER_GROUP_NAME, token_type::OPERATOR_GREATER},
    {OPERATOR_GREATER_EQUAL_GROUP_NAME, token_type::OPERATOR_GREATER_EQUAL},
    {OPERATOR_LESS_GROUP_NAME, token_type::OPERATOR_LESS},
    {OPERATOR_LESS_EQUAL_GROUP_NAME, token_type::OPERATOR_LESS_EQUAL},
    {OPERATOR_AND_GROUP_NAME, token_type::OPERATOR_AND},
    {OPERATOR_OR_GROUP_NAME, token_type::OPERATOR_OR},

    {KEYWORD_FOR_GROUP_NAME, token_type::KEYWORD_FOR},
    {KEYWORD_DO_GROUP_NAME, token_type::KEYWORD_DO},
    {KEYWORD_WHILE_GROUP_NAME, token_type::KEYWORD_WHILE},
    {KEYWORD_CONTINUE_GROUP_NAME, token_type::KEYWORD_CONTINUE},
    {KEYWORD_BREAK_GROUP_NAME, token_type::KEYWORD_BREAK},

    {COMMENT_MULTILINE_GROUP_NAME, token_type::COMMENT_MULTILINE},
    {COMMENT_ONE_LINER_GROUP_NAME, token_type::COMMENT_ONE_LINER},

    {KEYWORD_TRY_GROUP_NAME, token_type::KEYWORD_TRY},
    {KEYWORD_EXCEPTION_GROUP_NAME, token_type::KEYWORD_EXCEPTION},
    {KEYWORD_CATCH_GROUP_NAME, token_type::KEYWORD_CATCH},
    {KEYWORD_THROW_GROUP_NAME, token_type::KEYWORD_THROW},
    {KEYWORD_THROWS_GROUP_NAME, token_type::KEYWORD_THROWS},
};

token_type codesh::token::get_token_type(const std::string_view group_name)
{
    return GROUP_NAME_TO_TOKEN_TYPE.at(group_name);
}